"use client";
import { useState } from "react";
import { useRace } from "@/features/race-control/race-context";
import { RaceFrame, Field, clock, inputClass } from "@/components/race-frame";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { evaluateStopDuration } from "@/domain/race/rules";
import type { RacePit } from "@/domain/race/session";
import type { TeamView } from "@/domain/strategy/endurance";
export function BoxConsole(){const {race}=useRace();return <RaceFrame active="/box" title="Checklist de parada" description="Tempo de parada no relógio da prova; o sensor oficial e o regulamento da organização prevalecem."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{race?.views.filter(v=>v.team.driverIds.length>0).map(v=><PitCard key={v.team.id} view={v}/>)}</div><Card><CardHeader><CardTitle>Histórico de box</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="border-b text-left"><tr>{["Equipe","Entrada","Saída","Duração","Kart","Validade","Penalidade"].map(x=><th className="py-2" key={x}>{x}</th>)}</tr></thead><tbody>{race?.pits.slice().reverse().map(p=><tr key={p.id} className="border-b"><td className="py-3">{race.teams.find(t=>t.id===p.teamId)?.name}</td><td>{clock(p.enterMs)}</td><td>{clock(p.exitMs)}</td><td>{clock(p.durationMs)}</td><td>{p.oldKart} → {p.newKart??"—"}</td><td>{p.exitMs==null?"Em andamento":p.valid?"Válida":"Não confirmada / inválida"}</td><td>{p.penaltyLaps} volta(s)</td></tr>)}</tbody></table></CardContent></Card></RaceFrame>;}
function PitCard({view:v}:{view:TeamView}) {
  const {race,send,busy}=useRace();const [driver,setDriver]=useState("");const [kart,setKart]=useState("");const [checks,setChecks]=useState<RacePit["checks"]>({plate:false,sensor:false,weighed:false,ballast:false});
  if(!race)return null;
  const elapsed=v.pit?Math.max(0,race.elapsedMs-v.pit.enterMs):0;
  const valid=evaluateStopDuration(elapsed,race.config);
  return <Card><CardHeader><CardTitle>#{v.team.number} {v.team.name}</CardTitle></CardHeader><CardContent className="grid gap-3"><div className="flex justify-between"><Badge variant="outline">{v.completedStops}/{race.config.mandatoryStops} paradas</Badge><span className="text-sm">{v.remainingStops} restantes</span></div>{!v.pit?<Button disabled={busy} onClick={()=>void send({type:"pit-enter",teamId:v.team.id})}>Entrar no box</Button>:<><div className="font-mono text-4xl font-bold">{clock(elapsed)}</div><Badge variant={valid.status==="valid"?"ok":valid.status==="invalid"?"critical":"warning"}>{valid.status==="valid"?"Tempo cumprido":valid.status==="invalid"?"Ainda não conta":`Conta com penalidade de ${race.config.penaltyLaps} voltas`}</Badge><Field label="Próximo piloto"><select aria-label={`Próximo piloto ${v.team.number}`} className={inputClass} value={driver} onChange={e=>setDriver(e.target.value)}><option value="">Selecione</option>{race.drivers.filter(d=>v.team.driverIds.includes(d.id)&&d.active!==false).map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></Field><Field label="Kart sorteado"><input className={inputClass} value={kart} onChange={e=>setKart(e.target.value)}/></Field>{(Object.keys(checks) as (keyof RacePit["checks"])[]).map(key=><label className="flex items-center gap-2 text-sm" key={key}><input type="checkbox" checked={checks[key]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/>{{plate:"Placa conferida",sensor:"Sensor conferido",weighed:`Pesagem ≥ ${race.config.minimumWeightKg} kg`,ballast:"Lastro conferido"}[key]}</label>)}<Button disabled={busy||!driver||!kart||!Object.values(checks).every(Boolean)||valid.status==="invalid"} onClick={async()=>{if(await send({type:"pit-exit",teamId:v.team.id,driverId:driver,kart,checks})){setDriver("");setKart("");setChecks({plate:false,sensor:false,weighed:false,ballast:false});}}}>Liberar kart e registrar troca</Button><Button variant="outline" disabled={busy} onClick={()=>{if(confirm("Cancelar esta entrada de box?"))void send({type:"pit-cancel",teamId:v.team.id});}}>Cancelar entrada</Button></>}</CardContent></Card>;
}
