"use client";
import { useRace } from "@/features/race-control/race-context";
import { RaceFrame, clock, lapTime, delta } from "@/components/race-frame";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { LapChart } from "@/components/lap-chart";
export function LiveAnalysis({stints=false}:{stints?:boolean}){
  const {race}=useRace();const selected=race?.views.find(v=>v.team.id===race.selectedTeamId);
  const drivers=race?.analytics.drivers.filter(d=>selected?.team.driverIds.includes(d.id)).slice().sort((a,b)=>(a.performance.paceMs??Infinity)-(b.performance.paceMs??Infinity))??[];
  return <RaceFrame active={stints?"/stints":"/analysis"} title={stints?"Stints":"Driver Performance"} description="Comparação por ritmo válido, consistência e tendência; a melhor volta isolada não define o melhor piloto.">
    {!stints&&<Card><CardHeader><CardTitle>Pilotos da minha equipe</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="border-b text-left"><tr>{["Piloto","Voltas válidas","Stints","Tempo total","Best","Race pace","Mediana","MAD","Desvio","Degradação","Posições"].map(h=><th className="py-2" key={h}>{h}</th>)}</tr></thead><tbody>{drivers.map(d=><tr key={d.id} className="border-b"><td className="py-3 font-semibold">{d.name}</td><td>{d.performance.validCount}/{d.performance.count}</td><td>{d.stintCount}</td><td>{clock(d.timeMs)}</td><td>{lapTime(d.performance.bestMs)}</td><td>{lapTime(d.performance.paceMs)}</td><td>{lapTime(d.performance.medianMs)}</td><td>{lapTime(d.performance.madMs)}</td><td>{lapTime(d.performance.sdMs)}</td><td>{delta(d.performance.degradationMs)}</td><td>{d.positionsGained??"—"}</td></tr>)}</tbody></table>{!drivers.length&&<p className="py-4 text-muted-foreground">Cadastre e vincule pilotos à equipe para analisar.</p>}</CardContent></Card>}
    <Card><CardHeader><CardTitle>Histórico de stints</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[1200px] text-sm"><thead className="border-b text-left"><tr>{["Equipe","Piloto","Início / fim","Voltas","Duração","Válidas","Best / pior","Média / mediana","MAD / desvio","3 / 5 / 10","Tendência","Posições"].map(h=><th className="py-2" key={h}>{h}</th>)}</tr></thead><tbody>{race?.analytics.stints.filter(s=>s.teamId===selected?.team.id).slice().reverse().map(s=><tr key={s.id} className="border-b"><td className="py-3">{s.teamName}</td><td>{s.driverName}</td><td>{clock(s.startMs)} / {s.endMs==null?"Em pista":clock(s.endMs)}</td><td>{s.startLap}–{s.endLap??selected?.lapCount}</td><td>{clock(s.durationMs)}</td><td>{s.performance.validCount}/{s.performance.count}</td><td>{lapTime(s.performance.bestMs)} / {lapTime(s.performance.worstMs)}</td><td>{lapTime(s.performance.averageMs)} / {lapTime(s.performance.medianMs)}</td><td>{lapTime(s.performance.madMs)} / {lapTime(s.performance.sdMs)}</td><td>{lapTime(s.performance.last3Ms)} / {lapTime(s.performance.last5Ms)} / {lapTime(s.performance.last10Ms)}</td><td>{delta(s.performance.degradationMs)}</td><td>{s.positionsGained??"—"}</td></tr>)}</tbody></table></CardContent></Card>
    {selected&&race&&<Card><CardHeader><CardTitle>Histórico recente de voltas</CardTitle></CardHeader><CardContent><LapChart laps={race.laps[selected.team.id]??[]} medianMs={selected.pace.medianMs}/></CardContent></Card>}
    <p className="text-xs text-muted-foreground">Métricas históricas usam todas as voltas válidas registradas; Race Pace combina mediana, média aparada e janela recente. Degradação entre stints/pilotos é apenas tendência descritiva; compare condições semelhantes.</p>
  </RaceFrame>;
}
