import { describe,it,expect } from "vitest";
import { emptySession, validateConfig, type RaceLap } from "./session";
import { applyCommand, activeStint, driverTime, ingestLap } from "./engine";
import { performance, classifyLap } from "@/domain/pace/performance";
import { teamViews, connection, pitScenarios } from "@/domain/strategy/endurance";
import { parseCsv, parseRaceFile, normalizeLap, validateSnapshot, AuthorizedLapTimeProvider } from "@/domain/timing/providers";
import { simulateRace } from "@/domain/timing/simulation";
import { raceAnalytics } from "./analytics";
function session(){const s=emptySession();s.config.mandatoryStops=0;s.config.pitOpenAfterMs=0;s.config.pitCloseBeforeEndMs=0;s.config.stopMinimumMs=1000;s.config.stopPenaltyThresholdMs=1000;
  s.drivers=["a","b"].map(id=>({id,name:id,weightKg:80,ballastKg:20,preferredRole:"balanced" as const,stintCount:0,totalTimeMs:0}));
  s.teams=[{id:"t",name:"Nossa equipe",number:"17",kart:"17",category:"A",driverIds:["a","b"],role:"leader"}];s.selectedTeamId="t";applyCommand(s,{type:"driver-change",teamId:"t",driverId:"a"});return s;}
function lap(n:number,ms=47000,elapsed=n*47000):RaceLap{return {raceId:"kart-vicio",teamId:"t",lapNumber:n,lapTimeMs:ms,raceElapsedMs:elapsed,timestamp:elapsed,source:"MANUAL",quality:"MANUAL",kind:"normal"};}
describe("endurance performance and operational rules",()=>{
  it("preserves missing metrics rather than inventing pace or position",()=>{const s=session();ingestLap(s,{...lap(1),lapTimeMs:null});const v=teamViews(s)[0];expect(v.pace.paceMs).toBeNull();expect(v.position).toBeNull();expect(v.gapMs).toBeNull();expect(v.recommendation.confidence).toBeLessThan(.5);});
  it("excludes an isolated outlier without creating false degradation",()=>{const s=session();for(let n=1;n<=12;n++)ingestLap(s,lap(n));ingestLap(s,lap(13,85000));const v=teamViews(s)[0];expect(s.laps.t.at(-1)?.kind).toBe("outlier");expect(v.pace.medianMs).toBe(47000);expect(v.stintPace.degradationMs).toBe(0);expect(v.recommendation.action).toBe("CONTINUAR");});
  it("detects rising pace with rolling regression",()=>{const s=session();for(let n=1;n<=20;n++)ingestLap(s,lap(n,47000+n*70));const v=teamViews(s)[0];expect(v.stintPace.degradationMs).toBeGreaterThan(1000);expect(v.recommendation.action).toBe("BOX PRÓXIMA VOLTA");});
  it("provides robust consistency and recent 3/5/10 windows",()=>{const s=session();const p=performance(Array.from({length:10},(_,i)=>lap(i+1,47000+(i%2)*100)),s.config.thresholds);expect(p.madMs).toBe(50);expect(p.last5Ms).toBe(47100);expect(p.last10Ms).toBe(47050);expect(p.trimmedMeanMs).toBe(47050);});
  it("calls a mandatory pit at the stint limit even without pace",()=>{const s=session();s.elapsedMs=s.config.stintMaximumMs;expect(teamViews(s)[0].recommendation).toMatchObject({action:"BOX AGORA",confidence:1,rule:"stintMaximumMs"});});
  it("suspends pace decisions for stale timing",()=>{const s=session();s.source="LIVE";s.lastReceivedMs=100;expect(connection(s,100+s.config.thresholds.staleMs+1)).toBe("DELAYED");expect(teamViews(s,100+s.config.thresholds.staleMs+1)[0].recommendation.action).toBe("DADOS ATRASADOS");});
  it("deduplicates laps and does not manufacture missed lap times",()=>{const s=session();ingestLap(s,lap(1));ingestLap(s,lap(1));ingestLap(s,lap(5));expect(s.laps.t.map(l=>l.lapNumber)).toEqual([1,5]);});
  it("tracks driver swaps and accumulated time",()=>{const s=session();s.elapsedMs=120000;applyCommand(s,{type:"driver-change",teamId:"t",driverId:"b"});s.elapsedMs=180000;expect(driverTime(s,"a")).toBe(120000);expect(driverTime(s,"b")).toBe(60000);expect(activeStint(s,"t")?.driverId).toBe("b");expect(s.events.some(e=>e.type==="STINT_FINISHED")).toBe(true);});
  it("prevents simultaneous assignments of a driver",()=>{const s=session();s.teams.push({...s.teams[0],id:"t2",number:"22"});expect(()=>applyCommand(s,{type:"driver-change",teamId:"t2",driverId:"a"})).toThrow("outro kart");});
  it("blocks removing drivers with recorded stints",()=>{expect(()=>applyCommand(session(),{type:"driver-delete",driverId:"a"})).toThrow("stints");});
  it("blocks short pit exits and accepts a full checklist and change",()=>{const s=session();s.elapsedMs=10000;applyCommand(s,{type:"pit-enter",teamId:"t"});const command={type:"pit-exit" as const,teamId:"t",driverId:"b",kart:"99",checks:{plate:true,sensor:true,weighed:true,ballast:true}};expect(()=>applyCommand(s,command)).toThrow("mínimo");s.elapsedMs=12000;applyCommand(s,command);expect(s.pits[0]).toMatchObject({valid:true,durationMs:2000,newKart:"99",nextDriverId:"b"});expect(activeStint(s,"t")?.startMs).toBe(12000);});
  it("requires kart and driver changes when configured",()=>{const s=session();applyCommand(s,{type:"pit-enter",teamId:"t"});s.elapsedMs=10000;expect(()=>applyCommand(s,{type:"pit-exit",teamId:"t",driverId:"a",kart:"17",checks:{plate:true,sensor:true,weighed:true,ballast:true}})).toThrow("troca de kart");});
  it("respects minimum stint before entering pit",()=>{const s=session();s.config.stintMinimumMs=60000;expect(()=>applyCommand(s,{type:"pit-enter",teamId:"t"})).toThrow("Stint mínimo");});
  it("marks impossible mandatory driver time",()=>{const s=session();s.config.driverMinimumMs=s.config.durationMs;expect(teamViews(s)[0].recommendation.action).toBe("ESTRATÉGIA INVIÁVEL");});
  it("rejects a pit scenario before minimum stint",()=>{const s=session();s.config.stintMinimumMs=600000;for(let n=1;n<=6;n++)ingestLap(s,lap(n));const scenarios=pitScenarios(s,teamViews(s),"t");expect(scenarios.find(x=>x.waitLaps===0)?.violations).toContain("Stint mínimo");});
  it("supports manual metric exclusion without losing history",()=>{const s=session();for(let n=1;n<=6;n++)ingestLap(s,lap(n));applyCommand(s,{type:"lap-exclude",teamId:"t",lapNumber:3,excluded:true});expect(s.laps.t.length).toBe(6);expect(performance(s.laps.t,s.config.thresholds).validCount).toBe(5);});
  it("invalidates negative or impossible configuration",()=>{const s=session();expect(validateConfig({...s.config,stintMinimumMs:s.config.stintMaximumMs+1})).not.toEqual([]);expect(validateConfig({...s.config,durationMs:-1})).not.toEqual([]);});
  it("preserves pit and yellow laps outside pace",()=>{const s=session();expect(classifyLap({...lap(1),pitStatus:"enter"},[],s.config.thresholds)).toBe("in-lap");expect(performance([{...lap(1),kind:"yellow"},lap(2)],s.config.thresholds).validCount).toBe(1);});
  it("uses complete recorded history for driver analytics",()=>{const s=session();for(let n=1;n<=250;n++)ingestLap(s,lap(n));expect(raceAnalytics(s).drivers[0].performance.count).toBe(250);});
});
describe("authorized sources, imports and reproducibility",()=>{
  it("normalizes sparse rows and requires an explicit race clock",()=>{const s=session();expect(normalizeLap({number:"17",lapNumber:1,raceElapsedMs:47000},s)).toMatchObject({teamId:"t",lapTimeMs:null,quality:"MANUAL"});expect(()=>normalizeLap({number:"17",lapNumber:1},s)).toThrow("raceElapsedMs");});
  it("parses quoted CSV commas, semicolon and escaped quotes",()=>{expect(parseCsv('number;name\n17;"Equipe; A"')).toEqual([{number:"17",name:"Equipe; A"}]);expect(parseCsv('number,name\n17,"Equipe ""A"", B"')).toEqual([{number:"17",name:'Equipe "A", B'}]);});
  it("rejects malformed numeric fields and unknown teams",()=>{const s=session();expect(()=>normalizeLap({number:"17",lapNumber:1,lapTimeMs:-5,raceElapsedMs:1},s)).toThrow();expect(()=>normalizeLap({number:"99",lapNumber:1,raceElapsedMs:1},s)).toThrow("não cadastrada");});
  it("sorts replay by time and removes duplicate laps",()=>{const s=session();const data=[lap(2),lap(1),lap(1)];expect(parseRaceFile(JSON.stringify(data),"json",s).map(l=>l.lapNumber)).toEqual([1,2]);});
  it("validates snapshot entries deeply",()=>{expect(()=>validateSnapshot({capturedAtMs:1,raceClockMs:1,flag:"green",entries:[{entryNumber:"17",position:-1,lapCount:0}]})).toThrow();});
  it("does not connect to LapTime without official authorization",async()=>{await expect(new AuthorizedLapTimeProvider().getSnapshot()).rejects.toThrow("autorização");});
  it("generates deterministic races with pit and driver events",()=>{const s=session();s.config.durationMs=2*3600000;s.config.mandatoryStops=3;const a=simulateRace(s.config,3,3,42);const b=simulateRace(s.config,3,3,42);expect(a).toEqual(b);expect(a.teams.length).toBe(3);expect(a.drivers.length).toBe(9);expect(a.laps.some(l=>l.pitStatus==="enter")).toBe(true);expect(a.laps.some(l=>l.pitStatus==="exit")).toBe(true);expect(a.laps.every((l,i)=>!i||l.raceElapsedMs>=a.laps[i-1].raceElapsedMs)).toBe(true);});
});
