"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useRace } from "./race-context";
import { RaceFrame, Stat, clock, lapTime, delta, inputClass } from "@/components/race-frame";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { LapChart } from "@/components/lap-chart";
export function RaceDashboard({command=false,readonly=false}:{command?:boolean;readonly?:boolean}) {
  const {race,busy,connectionError,send}=useRace();const [nextDriver,setNextDriver]=useState("");
  const me=race?.views.find(v=>v.team.id===race.selectedTeamId);
  const alerts=useMemo(()=>race?.events.filter(e=>e.type==="ALERT"||e.severity==="CRÍTICO").slice(-6).reverse()??[],[race?.events]);
  const laps=me?race?.laps[me.team.id]??[]:[];
  const recommendation=connectionError?"DADOS INDISPONÍVEIS":me?.recommendation.action??"CONFIGURAR EQUIPE";
  return <RaceFrame active={readonly?"/ipad":command?"/command":"/"} title={command?"Race Command Center":readonly?"Race Follow":"Race Control"} description="Posição, ritmo, stint e decisão de box em uma única leitura." command={command}>
    {race&&!race.teams.length&&<Card><CardContent className="grid gap-3 p-6"><h2 className="text-xl font-bold">Prepare sua prova</h2><p>Configure o regulamento, cadastre pilotos e equipes ou carregue uma corrida simulada.</p><div className="flex gap-3"><Link href="/setup"><Button>Configurar prova</Button></Link><Link href="/replay"><Button variant="outline">Testar simulação</Button></Link></div></CardContent></Card>}
    {race&&me&&<>
      <section className="grid gap-3 md:grid-cols-4"><Stat label="Onde estamos" value={me.position==null?"—":`P${me.position}`} /><Stat label="Piloto atual" value={me.driverName}/><Stat label={`STINT · ${me.classification}`} value={delta(me.paceDeltaMs)}/><Stat label="PIT · o que fazer agora" value={recommendation}/></section>
      <section className="grid gap-3 xl:grid-cols-[1fr_420px]">
        <Card><CardHeader><CardTitle>#{me.team.number} {me.team.name} · kart {me.team.kart}</CardTitle></CardHeader><CardContent className="grid gap-4">
          <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Race pace" value={lapTime(me.pace.paceMs)}/><Stat label="Última volta" value={lapTime(me.lastLapMs)}/><Stat label="Best lap válida" value={lapTime(me.pace.bestMs)}/><Stat label="Gap para líder" value={me.gapLabel}/><Stat label="Últimas 5 / 10" value={`${lapTime(me.pace.last5Ms)} / ${lapTime(me.pace.last10Ms)}`}/><Stat label="Consistência MAD" value={me.stintPace.madMs==null?"—":`±${(me.stintPace.madMs/1000).toFixed(3)} s`}/><Stat label="Degradação por regressão" value={delta(me.stintPace.degradationMs)}/><Stat label="Paradas obrigatórias" value={`${me.completedStops}/${race.config.mandatoryStops}`}/></div>
          <div className="flex items-center justify-between text-sm"><span>Stint {race.stints.filter(s=>s.teamId===me.team.id).length} · {clock(me.stintElapsedMs)}</span><strong>Limite {clock(race.config.stintMaximumMs)}</strong></div><Progress value={me.stintElapsedMs/race.config.stintMaximumMs*100} indicatorClassName={me.stintElapsedMs>=race.config.stintCriticalMs?"bg-red-600":me.stintElapsedMs>=race.config.stintWarningMs?"bg-amber-500":"bg-emerald-600"}/>
          {!readonly&&<div className="flex flex-wrap gap-2"><select aria-label="Piloto atual" className={`${inputClass} max-w-xs`} value={nextDriver||me.stint?.driverId||""} onChange={e=>setNextDriver(e.target.value)}><option value="">Selecione o piloto</option>{race.drivers.filter(d=>me.team.driverIds.includes(d.id)&&d.active!==false).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><Button disabled={busy||!nextDriver||!!me.pit} onClick={async()=>{if(await send({type:"driver-change",teamId:me.team.id,driverId:nextDriver}))setNextDriver("");}}>Registrar piloto</Button>{!me.pit?<Button disabled={busy} variant="outline" onClick={()=>void send({type:"pit-enter",teamId:me.team.id})}>Entrar no box</Button>:<Link href="/box"><Button>Checklist e saída do box</Button></Link>}<Link href="/command"><Button variant="outline">Modo telão</Button></Link></div>}
          <LapChart laps={laps} medianMs={me.stintPace.medianMs}/>
        </CardContent></Card>
        <div className="grid content-start gap-3"><Card className={recommendation.includes("AGORA")?"border-red-300":""}><CardHeader><CardTitle>Engenheiro de corrida</CardTitle></CardHeader><CardContent className="grid gap-3"><div className="text-2xl font-bold">{recommendation}</div><Badge variant="info">PIT WINDOW · {me.recommendation.window}</Badge><p>{me.recommendation.reason}</p><p className="text-sm text-muted-foreground">Confiança {connectionError?0:Math.round(me.recommendation.confidence*100)}% · faltam {me.remainingStops} paradas</p><p>Próximo piloto: <strong>{race.drivers.find(d=>d.id===me.nextDriverId)?.name??"Dados insuficientes"}</strong></p><details className="rounded-md border border-border p-3"><summary className="cursor-pointer font-semibold">Por quê?</summary><p className="mt-2 text-sm">Regra: {me.recommendation.rule}</p><dl className="mt-2 text-xs">{Object.entries(me.recommendation.metrics).map(([k,v])=><div key={k} className="flex justify-between gap-2"><dt>{k}</dt><dd>{v==null?"Dados insuficientes":Math.round(v)}</dd></div>)}</dl><p className="mt-2 text-xs">Tempos em ms; projeções são estimativas. Thresholds em Setup.</p></details></CardContent></Card>
          <Card><CardHeader><CardTitle>Battle Monitor</CardTitle></CardHeader><CardContent className="grid gap-3">{(["ahead","behind"] as const).map(key=>{const rival=race.battle[key];return <div key={key} className="rounded-md border border-border p-3"><div className="text-xs text-muted-foreground">{key==="ahead"?"À frente":"Atrás"}</div>{rival?<><strong>P{rival.position} · {rival.name}</strong><div className="mt-1 text-sm">Gap {lapTime(rival.gapMs)} · ganho {delta(rival.gainMs)}/volta</div><div className="text-sm">{key==="ahead"?(rival.catchLaps!=null?`Alcança em ~${rival.catchLaps} voltas`:"Sem aproximação calculável"):(rival.gainMs!=null&&rival.gainMs<0&&rival.gapMs!=null?`Pode nos alcançar em ~${Math.ceil(rival.gapMs/-rival.gainMs)} voltas`:"Sem ameaça calculável")}</div></>:<p>Dados insuficientes</p>}</div>;})}</CardContent></Card>
        </div>
      </section>
      <section className="grid gap-3 xl:grid-cols-[1fr_420px]"><Card><CardHeader><CardTitle>Classificação e ritmo</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="border-b text-left text-xs uppercase text-muted-foreground"><tr>{["Pos","Equipe / kart","Voltas","Última","Melhor","Pace 5","Gap","Paradas","Stint"].map(h=><th className="py-2" key={h}>{h}</th>)}</tr></thead><tbody>{race.views.map(v=><tr key={v.team.id} className={`border-b border-border ${v.team.id===me.team.id?"bg-sky-50 font-semibold":""}`}><td className="py-3">{v.position==null?"—":`P${v.position}`}</td><td><button onClick={()=>void send({type:"select-team",teamId:v.team.id})}>#{v.team.number} {v.team.name} / {v.team.kart}</button></td><td>{v.lapCount}</td><td>{lapTime(v.lastLapMs)}</td><td>{lapTime(v.pace.bestMs)}</td><td>{lapTime(v.pace.last5Ms)}</td><td>{v.gapLabel}</td><td>{v.completedStops}</td><td>{clock(v.stintElapsedMs)}</td></tr>)}</tbody></table></CardContent></Card>
        <Card><CardHeader><CardTitle>Alertas priorizados</CardTitle></CardHeader><CardContent className="grid gap-2">{!alerts.length&&<p className="text-sm text-muted-foreground">Sem alertas registrados.</p>}{alerts.map(a=><div key={a.id} className={`rounded-md border p-3 text-sm ${a.severity==="CRÍTICO"?"border-red-200 bg-red-50":"border-amber-200 bg-amber-50"}`}><strong>{a.severity} · {clock(a.elapsedMs)}</strong><p>{race.teams.find(t=>t.id===a.teamId)?.name}: {a.message}</p></div>)}</CardContent></Card></section>
    </>}
  </RaceFrame>;
}
