"use client";
import { useRace } from "./race-context";
import { RaceFrame, clock, lapTime, Stat } from "@/components/race-frame";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { suggestAllocation } from "@/domain/strategy/allocation";
export function StrategyConsole(){
  const {race,send,busy}=useRace();const me=race?.views.find(v=>v.team.id===race.selectedTeamId);
  const plan=me&&race?suggestAllocation({drivers:race.drivers.filter(d=>me.team.driverIds.includes(d.id)&&d.active!==false),entries:[{id:me.team.id,number:me.team.number,role:me.team.role}],stints:me.remainingStops+1,pressureReady:new Set(race.drivers.filter(d=>d.pressureReady).map(d=>d.id)),pressureStints:Math.min(2,me.remainingStops+1)}):{};
  return <RaceFrame active="/strategy" title="Estratégia e projeções" description="Regras determinísticas, alternativas de pit e obrigações de cada piloto.">
    {race&&me&&<><div className="flex flex-wrap gap-2"><Button variant={race.strategyMode==="performance"?"default":"outline"} disabled={busy} onClick={()=>void send({type:"strategy-mode",mode:"performance"})}>Performance</Button><Button variant={race.strategyMode==="participation"?"default":"outline"} disabled={busy} onClick={()=>void send({type:"strategy-mode",mode:"participation"})}>Participação</Button></div><section className="grid gap-3 sm:grid-cols-4"><Stat label="Paradas restantes" value={me.remainingStops}/><Stat label="Stints restantes estimados" value={me.remainingStops+1}/><Stat label="Perda estimada por pit" value={clock(race.config.stopMinimumMs+race.config.pitLossMs+race.config.driverChangeMs)}/><Stat label="Ação recomendada" value={me.recommendation.action}/></section>
      <Card><CardHeader><CardTitle>Tempo regulamentar dos pilotos</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="border-b text-left"><tr>{["Piloto","Já pilotou","Mínimo restante","Pode pilotar","Stints faltantes","Pace"].map(x=><th className="py-2" key={x}>{x}</th>)}</tr></thead><tbody>{me.obligations.map(o=><tr key={o.id} className="border-b"><td className="py-3">{o.name}</td><td>{clock(o.timeMs)}</td><td>{clock(o.remainingMinimumMs)}</td><td>{clock(o.availableMs)}</td><td>{o.remainingStints}</td><td>{lapTime(o.pace.paceMs)}</td></tr>)}</tbody></table></CardContent></Card>
      <Card><CardHeader><CardTitle>Strategy Simulator · projeções dinâmicas</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{race.scenarios.slice(0,12).map((s,i)=><div key={`${s.waitLaps}-${s.driverId}`} className={`rounded-md border p-4 ${i===0&&s.legal?"border-emerald-300 bg-emerald-50":"border-border"}`}><div className="mb-2 flex flex-wrap gap-2"><Badge variant={s.legal?"ok":"critical"}>{s.legal?"Viável nas regras verificadas":"Não viável"}</Badge>{i===0&&s.legal&&s.finishPosition!=null&&<Badge variant="info">Melhor projeção atual</Badge>}</div><h3 className="font-bold">{s.waitLaps?`Box em ${s.waitLaps} voltas`:"Box agora"} · {s.driverName}</h3><dl className="mt-2 grid gap-1 text-sm"><div>Pace esperado: {lapTime(s.expectedPaceMs)}</div><div>Pit total: {clock(s.pitLossMs)}</div><div>Retorno: {s.returnPosition==null?"Dados insuficientes":`P${s.returnPosition}`} · tráfego {s.traffic}</div><div>Final: {s.finishPosition==null?"Dados insuficientes":`P${s.finishPosition}`} {s.interval?`(P${s.interval[0]}–P${s.interval[1]})`:""}</div><div>{s.cut}</div></dl>{s.violations.length>0&&<p className="mt-2 text-xs text-red-700">{s.violations.join("; ")}</p>}</div>)}{!race.scenarios.length&&<p>Cadastre outros pilotos e obtenha voltas válidas para comparar estratégias.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Plano sugerido de pilotos</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2">{Object.entries(plan).flatMap(([,ids])=>ids.map((id,i)=><Badge key={`${id}-${i}`} variant="outline">S{i+1}: {race.drivers.find(d=>d.id===id)?.name??id}</Badge>))}</div><p className="mt-3 text-sm text-muted-foreground">Alocação por preferência e disponibilidade. Confira duração de cada stint, tempos mínimos, limites e pilotos compartilhados antes de executar. Cenários calculam tempo restante, limites de stint, janela e disponibilidade; posição final exige ritmo de todas as equipes. Faixa mostrada é uma margem heurística, sem garantia estatística.</p></CardContent></Card>
    </>}
  </RaceFrame>;
}
