"use client";
import { useState } from "react";
import Link from "next/link";
import { useRace } from "./race-context";
import { RaceFrame, Field, inputClass, lapTime, clock } from "@/components/race-frame";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { LapChart } from "@/components/lap-chart";
export function TimingConsole(){
  const {race,send,busy}=useRace();const [lap,setLap]=useState("");const [ms,setMs]=useState("");const [elapsed,setElapsed]=useState("");const [position,setPosition]=useState("");const [gap,setGap]=useState("");const [payload,setPayload]=useState("");const [error,setError]=useState("");
  const me=race?.views.find(v=>v.team.id===race.selectedTeamId);
  return <RaceFrame active="/monitoring" title="Live Timing" description="Entrada manual ou dados normalizados de uma fonte expressamente autorizada.">
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Registrar volta da minha equipe</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Número da volta"><input type="number" min="1" className={inputClass} value={lap} placeholder={String((me?.lapCount??0)+1)} onChange={e=>setLap(e.target.value)}/></Field><Field label="Tempo da volta (segundos)"><input type="number" step="0.001" min="0" className={inputClass} value={ms} onChange={e=>setMs(e.target.value)}/></Field><Field label="Tempo decorrido de corrida (segundos)"><input type="number" step="0.001" className={inputClass} value={elapsed} placeholder={String((race?.elapsedMs??0)/1000)} onChange={e=>setElapsed(e.target.value)}/></Field><Field label="Posição (opcional)"><input type="number" min="1" className={inputClass} value={position} onChange={e=>setPosition(e.target.value)}/></Field><Field label="Gap para líder (s ou '1 volta')"><input className={inputClass} value={gap} onChange={e=>setGap(e.target.value)}/></Field></div><Button disabled={busy||!me||!ms} onClick={async()=>{if(!race||!me)return;const accepted=await send({type:"normalized-laps",laps:[{teamId:me.team.id,lapNumber:Number(lap||me.lapCount+1),lapTimeMs:Number(ms)*1000,raceElapsedMs:elapsed?Number(elapsed)*1000:race.elapsedMs,position:position?Number(position):undefined,gap:gap||undefined,source:"MANUAL",quality:"MANUAL"}]});if(accepted){setLap("");setMs("");}}}>Registrar volta</Button><p className="text-xs text-muted-foreground">Sem posição ou gap informados, essas métricas permanecem indisponíveis. Tempo de volta em segundos; o modelo interno usa milissegundos.</p></CardContent></Card>
      <Card><CardHeader><CardTitle>Ingestão autorizada</CardTitle></CardHeader><CardContent className="grid gap-3"><p className="text-sm">Cole um snapshot normalizado ou uma lista de voltas JSON. Para automação, use POST /api/timing com Bearer TIMING_API_KEY configurado no servidor.</p><textarea aria-label="JSON de cronometragem" className="min-h-48 w-full rounded-md border border-border p-3 font-mono text-xs" value={payload} onChange={e=>setPayload(e.target.value)} placeholder='[{"number":"17","lapNumber":1,"lapTimeMs":46820,"raceElapsedMs":46820}]'/><Button disabled={busy||!payload} onClick={async()=>{try{const data=JSON.parse(payload);if(Array.isArray(data))await send({type:"normalized-laps",laps:data});else {const response=await fetch((await import("@/lib/app-url")).appUrl("/api/timing"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({snapshot:data})});const result=await response.json();if(!response.ok)throw new Error(result.error);}setError("");}catch(e){setError(e instanceof Error?e.message:"JSON inválido.");}}}>Receber JSON</Button>{error&&<p role="alert" className="text-red-700">{error}</p>}<p className="rounded-md bg-amber-50 p-3 text-sm text-amber-900">LapTime/SISECOM: integração desativada até autorização escrita e documentação oficial. O sistema funciona com entrada manual, JSON/CSV, replay e simulação.</p><Link className="text-sm text-sky-700 underline" href="/replay">Importar arquivo ou carregar simulação</Link></CardContent></Card></div>
    {race&&me&&<Card><CardHeader><CardTitle>Cronometragem · #{me.team.number} · {me.team.name}</CardTitle></CardHeader><CardContent className="grid gap-3"><LapChart laps={race.laps[me.team.id]??[]} medianMs={me.pace.medianMs}/><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="border-b text-left"><tr>{["Volta","Tempo","Corrida","Pos","Fonte","Qualidade","Tipo","Métricas"].map(h=><th className="py-2" key={h}>{h}</th>)}</tr></thead><tbody>{(race.laps[me.team.id]??[]).slice(-50).reverse().map(l=><tr key={l.lapNumber} className="border-b border-border"><td className="py-2">{l.lapNumber}</td><td>{lapTime(l.lapTimeMs)}</td><td>{clock(l.raceElapsedMs)}</td><td>{l.position??"—"}</td><td>{l.source}</td><td>{l.quality}</td><td>{l.kind}</td><td><Button size="sm" variant="outline" disabled={busy} onClick={()=>void send({type:"lap-exclude",teamId:me.team.id,lapNumber:l.lapNumber,excluded:!l.excluded})}>{l.excluded?"Reincluir":"Excluir"}</Button></td></tr>)}</tbody></table></div><p className="text-xs text-muted-foreground">Voltas anômalas são preservadas no histórico e excluídas automaticamente do ritmo. Revisão manual acima controla a exclusão adicional.</p></CardContent></Card>}
  </RaceFrame>;
}
