"use client";
import { useState } from "react";
import { useRace } from "@/features/race-control/race-context";
import { RaceFrame, Field, inputClass } from "@/components/race-frame";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { RaceTeam } from "@/domain/race/session";
export default function TeamsPage(){
  const {race,send,busy}=useRace();const [draft,setDraft]=useState<RaceTeam|null>(null);const [importError,setImportError]=useState("");
  const fresh=():RaceTeam=>({id:crypto.randomUUID(),number:"",name:"",kart:"",category:"Endurance",driverIds:[],role:"support"});
  const update=(patch:Partial<RaceTeam>)=>setDraft(d=>d?{...d,...patch}:d);
  return <RaceFrame active="/teams" title="Equipes" description="Cadastre os inscritos, associe pilotos e selecione sua equipe.">
    <div className="flex flex-wrap gap-3"><Button onClick={()=>setDraft(fresh())}>Nova equipe</Button><label className="cursor-pointer rounded-md border border-border px-4 py-2 text-sm">Importar equipes JSON<input className="sr-only" type="file" accept=".json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;const teams=JSON.parse(await file.text()) as RaceTeam[];if(!Array.isArray(teams))throw new Error("Use uma lista JSON de equipes.");for(const team of teams){if(!await send({type:"team-save",team:{...team,id:team.id||crypto.randomUUID(),driverIds:team.driverIds??[],role:team.role??"support"}}))break;}setImportError("");}catch(err){setImportError(err instanceof Error?err.message:"Arquivo inválido");}e.target.value="";}}/></label></div>{importError&&<p role="alert" className="text-red-700">{importError}</p>}
    {draft&&<Card><CardHeader><CardTitle>{race?.teams.some(t=>t.id===draft.id)?"Editar equipe":"Nova equipe"}</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2">{(["number","name","kart","category"] as const).map(key=><Field key={key} label={{number:"Número de inscrição",name:"Nome",kart:"Kart físico",category:"Categoria"}[key]}><input className={inputClass} value={draft[key]} onChange={e=>update({[key]:e.target.value})}/></Field>)}<Field label="Papel estratégico"><select className={inputClass} value={draft.role} onChange={e=>update({role:e.target.value as RaceTeam["role"]})}>{["leader","attack","support","recovery"].map(role=><option key={role}>{role}</option>)}</select></Field></div><div><div className="mb-2 text-sm font-semibold">Pilotos vinculados</div><div className="grid gap-2 sm:grid-cols-3">{race?.drivers.map(d=><label key={d.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.driverIds.includes(d.id)} onChange={e=>update({driverIds:e.target.checked?[...draft.driverIds,d.id]:draft.driverIds.filter(id=>id!==d.id)})}/>{d.name}</label>)}</div>{!race?.drivers.length&&<p className="text-muted-foreground">Cadastre pilotos primeiro na tela Pilotos.</p>}</div><div className="flex gap-2"><Button disabled={busy||!draft.number.trim()||!draft.name.trim()} onClick={async()=>{if(await send({type:"team-save",team:draft}))setDraft(null);}}>Salvar equipe</Button><Button variant="outline" onClick={()=>setDraft(null)}>Cancelar</Button></div></CardContent></Card>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{race?.teams.map(t=><Card key={t.id}><CardHeader><CardTitle>#{t.number} {t.name}</CardTitle></CardHeader><CardContent className="grid gap-3"><p className="text-sm">Kart {t.kart||"—"} · {t.category} · {t.driverIds.length} pilotos</p><p className="text-sm text-muted-foreground">{t.driverIds.map(id=>race.drivers.find(d=>d.id===id)?.name).join(", ")}</p>{race.selectedTeamId===t.id&&<Badge variant="ok">MINHA EQUIPE</Badge>}<div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy} onClick={()=>void send({type:"select-team",teamId:t.id})}>Acompanhar</Button><Button size="sm" variant="outline" onClick={()=>setDraft(structuredClone(t))}>Editar</Button><Button size="sm" variant="outline" onClick={()=>{if(confirm(`Remover ${t.name}?`))void send({type:"team-delete",teamId:t.id});}}>Remover</Button></div></CardContent></Card>)}</div>
  </RaceFrame>;
}
