"use client";
import { useState } from "react";
import { useRace } from "@/features/race-control/race-context";
import { RaceFrame, Field, inputClass, clock } from "@/components/race-frame";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { appUrl } from "@/lib/app-url";
import type { RaceSession } from "@/domain/race/session";
export default function ReplayPage(){
  const {race,send,busy}=useRace();const [count,setCount]=useState(15);const [drivers,setDrivers]=useState(3);const [seed,setSeed]=useState(42);const [fileText,setFileText]=useState("");const [format,setFormat]=useState<"json"|"csv">("json");const [name,setName]=useState("");const [error,setError]=useState("");
  return <RaceFrame active="/replay" title="Replay e simulação" description="Teste a operação completa sem depender de serviços externos.">
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Gerar prova simulada</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="text-sm text-muted-foreground">Usa duração, regras e paradas do Setup. Gera voltas, degradação, tráfego, incidentes, pit e trocas de pilotos. Substitui os cadastros desta sessão; exporte antes de carregar.</p><div className="grid gap-3 sm:grid-cols-3"><Field label="Equipes"><input type="number" min="1" max={race?.config.maxTeams} className={inputClass} value={count} onChange={e=>setCount(Number(e.target.value))}/></Field><Field label="Pilotos por equipe"><input type="number" min={race?.config.minDrivers} max={race?.config.maxDrivers} className={inputClass} value={drivers} onChange={e=>setDrivers(Number(e.target.value))}/></Field><Field label="Semente (reprodutível)"><input type="number" className={inputClass} value={seed} onChange={e=>setSeed(Number(e.target.value))}/></Field></div><Button disabled={busy} onClick={()=>{if(confirm("Carregar simulação e substituir a sessão atual? Exporte um backup antes."))void send({type:"simulation",teamCount:count,driversPerTeam:drivers,seed,speed:10});}}>Carregar simulação</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>Carregar JSON / CSV</CardTitle></CardHeader><CardContent className="grid gap-3"><input aria-label="Arquivo de corrida" type="file" accept=".json,.csv" className="text-sm" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>25*1024*1024){setError("Limite de 25 MB.");return;}setName(file.name);setFormat(file.name.toLowerCase().endsWith(".csv")?"csv":"json");setFileText(await file.text());setError("");}}/><p className="text-sm text-muted-foreground">Campos: teamId ou number, lapNumber, lapTimeMs, raceElapsedMs. opcionais: driverId, kartNumber, position, gap, kind, pitStatus, quality. JSON exportado inclui cadastros e configuração; CSV usa as equipes cadastradas.</p><p className="text-sm">{name||"Nenhum arquivo selecionado"}</p><div className="flex flex-wrap gap-2"><Button disabled={!fileText||busy} onClick={()=>{if(confirm("Carregar replay e reiniciar o histórico atual?"))void send({type:"import",text:fileText,format,replay:true});}}>Carregar replay</Button><Button variant="outline" disabled={!fileText||busy} onClick={()=>void send({type:"import",text:fileText,format,replay:false})}>Importar voltas</Button><Button variant="outline" disabled={!fileText||busy||format!=="json"} onClick={()=>{try{const session=JSON.parse(fileText) as RaceSession;if(confirm("Restaurar o backup completo nesta sessão?"))void send({type:"restore",session});}catch{setError("JSON inválido.");}}}>Restaurar backup</Button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}</CardContent></Card></div>
    {race?.playback&&<Card><CardHeader><CardTitle>Controle de reprodução</CardTitle></CardHeader><CardContent className="grid gap-3"><div className="flex flex-wrap items-center gap-3"><Button disabled={busy||race.playback.cursor===race.playback.total} onClick={()=>void send({type:"playback",action:race.playback?.running?"pause":"play"})}>{race.playback.running?"Pausar":"Reproduzir"}</Button><Field label="Velocidade"><select className={inputClass} value={race.playback.speed} onChange={e=>void send({type:"playback",action:"speed",speed:Number(e.target.value)})}>{[1,2,5,10,60,0].map(v=><option key={v} value={v}>{v===0?"MAX":`${v}x`}</option>)}</select></Field><strong className="font-mono">{clock(race.elapsedMs)}</strong><span className="text-sm">{race.playback.cursor.toLocaleString("pt-BR")} / {race.playback.total.toLocaleString("pt-BR")} eventos de volta</span></div><Progress value={race.playback.cursor/race.playback.total*100}/><p className="text-xs text-muted-foreground">A reprodução usa os horários originais de corrida e preserva a ordem dos eventos. MAX processa lotes limitados para manter a interface responsiva.</p></CardContent></Card>}
    <Card><CardHeader><CardTitle>Backup e encerramento</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3"><a href={appUrl("/api/race?export=1")} download className="rounded-md border border-border px-4 py-2 text-sm font-semibold">Exportar corrida completa JSON</a><Button variant="outline" disabled={busy} onClick={()=>{if(confirm("Encerrar a prova e fechar os stints ativos?"))void send({type:"clock",action:"finish"});}}>Encerrar prova</Button><Button variant="outline" disabled={busy} onClick={()=>{if(confirm("Apagar voltas, stints, paradas e eventos? Cadastros serão preservados. Exporte antes."))void send({type:"reset"});}}>Nova sessão mantendo cadastros</Button></CardContent></Card>
  </RaceFrame>;
}
